### ISSUE TITLE
regtok delete is broken

### ISSUE THREAD

**Issue by andreiz** [JOJ0/synadm#110]
I'm using 0.41.2 (git clone of the repo). Running `synadm regtok delete <token>` results in:

```
Traceback (most recent call last):
  File "/root/code/synadm/.venv/bin/synadm", line 33, in <module>
    sys.exit(load_entry_point('synadm', 'console_scripts', 'synadm')())
  File "/root/code/synadm/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/code/synadm/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/code/synadm/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/code/synadm/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/code/synadm/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/code/synadm/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/code/synadm/.venv/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/root/code/synadm/synadm/cli/regtok.py", line 146, in regtok_delete
    response = helper.api.regtok_delete(token)
  File "/root/code/synadm/synadm/api.py", line 1261, in regtok_delete
    return self.query("delete", "v1/registration_tokens/{token}",
  File "/root/code/synadm/synadm/api.py", line 114, in query
    urlpart = urlpart.format(*args, **kwargs)
KeyError: 'token'
```

The rest of the commands seem to  work.

**Comment by andreiz** [comment]
```
# git describe
v0.41.2-11-g11c7db7
```

**Comment by andreiz** [comment]
`$ synadm regtok delete "mytoken"

Nothing out of the ordinary. 

The token seems to persist in the `context.params` at least until here:

`  File "/root/code/synadm/.venv/lib/python3.10/site-packages/click/core.py", line 1658`

For what it's worth, it pulled in `click-8.1.3` when I ran `setup.py develop`

**Comment by JOJ0** [comment]
Thanks @andreiz for that catch and thanks @JacksonChen666 for fixing :+1: PR approved.
