### ISSUE TITLE
Add feature to see synadm version

### ISSUE THREAD

**Issue by jahway603** [JOJ0/synadm#115]
I was running synadm v 0.38 (as seen in my local setup.py) and followed the [update git installation section](https://github.com/JOJ0/synadm#update-git-installation) (which has been successful in the past for me).

I get the following errors when running `pip install .`
```
$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/dietpi/synadm
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Click<9.0,>=7.1 in /usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg (from synadm==0.42) (7.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from synadm==0.42) (2.26.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.9/dist-packages/tabulate-0.8.9-py3.9.egg (from synadm==0.42) (0.8.9)
Requirement already satisfied: PyYaml in /usr/local/lib/python3.9/dist-packages (from synadm==0.42) (5.4.1)
Requirement already satisfied: click-option-group>=0.5.2 in /usr/local/lib/python3.9/dist-packages/click_option_group-0.5.3-py3.9.egg (from synadm==0.42) (0.5.3)
Requirement already satisfied: dnspython in /usr/local/lib/python3.9/dist-packages/dnspython-2.3.0-py3.9.egg (from synadm==0.42) (2.3.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->synadm==0.42) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->synadm==0.42) (2021.5.30)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->synadm==0.42) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->synadm==0.42) (2.0.6)
Building wheels for collected packages: synadm
  Building wheel for synadm (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying synadm/api.py -> build/lib/synadm
      error: could not delete 'build/lib/synadm/api.py': Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for synadm
  Running setup.py clean for synadm
Failed to build synadm
Installing collected packages: synadm
  Attempting uninstall: synadm
    Found existing installation: synadm 0.33.1
    Uninstalling synadm-0.33.1:
      Successfully uninstalled synadm-0.33.1
  Running setup.py install for synadm ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for synadm did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      /home/dietpi/.local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      copying synadm/api.py -> build/lib/synadm
      error: could not delete 'build/lib/synadm/api.py': Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of synadm
  Moving to /home/dietpi/.local/bin/synadm
   from /tmp/pip-uninstall-onmzdjc2/synadm
  Moving to /home/dietpi/.local/lib/python3.9/site-packages/synadm-0.33.1.dist-info/
   from /home/dietpi/.local/lib/python3.9/site-packages/~ynadm-0.33.1.dist-info
  Moving to /home/dietpi/.local/lib/python3.9/site-packages/synadm/
   from /home/dietpi/.local/lib/python3.9/site-packages/~ynadm
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> synadm

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
--- Logging error ---
Traceback (most recent call last):
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_vendor/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_vendor/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_vendor/rich/segment.py", line 249, in split_lines
    for segment in segments:
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_vendor/rich/console.py", line 1283, in render
    renderable = rich_cast(renderable)
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.9/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip'
Call stack:
  File "/usr/local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/self_outdated_check.py", line 236, in pip_self_version_check
    logger.warning("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.9/logging/__init__.py", line 1454, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/home/dietpi/.local/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.2.2', new='23.2.1'),)
```

After looking at these errors, it makes me think I'm running v 0.33.1 but I thought I was running v 0.38 and I want to be running the latest v 0.42. When I run `synadm -h` it's not clear what version I'm actually running/using. Is there another way to check this or fix this?

**Comment by JOJ0** [comment]
I'd like to second what @JacksonChen666 said: Installing from pypi directly is the best way. We usually try to release as soon as we have new features in our master branch, so most of the time you will get a pretty "latest" synadm that way.

The permission error above is indeed intersting. You could simply check that path with `ls -l`and see if it really is a permission thing. Anyway, this seems too weird to fix manually, I suggest you try uninstalling synadm completely (your config usually is in ~/.config/synadm.yaml and should not be bothered by that)

Here's some more detail on how to find out where and how your synadm and your Python packages are actually installed:
https://pip.pypa.io/en/stable/cli/pip_list/

**Comment by JOJ0** [comment]
@jahway603 did this work for you? Can we close this issue?

**Comment by jahway603** [comment]
@JOJ0 I followed the PyPI install method and that worked to install the latest version.

@JacksonChen666 is correct that the feature to see the synadm version is not implemented.
