### ISSUE TITLE
catch error on incomplete config after "auto-reconfigure"

### ISSUE THREAD

**Issue by JOJ0** [JOJ0/synadm#13]
Catch error when user execs a regular command eg. `synadm user list` - config is found to be incomplete - configurator is launched autoatically - user again does not enter all requirded information.

Either error should be catched or configuator should force user to input all required information and don't accept input empty strings (eg by just hitting enter)

```
ERROR config entry user missing
Traceback (most recent call last):
  File "/Users/jojo/.venvs/synadm_after_pr/bin/synadm", line 11, in <module>
    load_entry_point('synadm==0.14', 'console_scripts', 'synadm')()
  File "/Users/jojo/.venvs/synadm_after_pr/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jojo/.venvs/synadm_after_pr/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jojo/.venvs/synadm_after_pr/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jojo/.venvs/synadm_after_pr/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jojo/.venvs/synadm_after_pr/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jojo/.venvs/synadm_after_pr/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jojo/.venvs/synadm_after_pr/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/jojo/.venvs/synadm_after_pr/lib/python3.7/site-packages/synadm-0.14-py3.7.egg/synadm/cli/user.py", line 47, in list_user_cmd
AttributeError: 'NoneType' object has no attribute 'user_list'
```

**Comment by JOJ0** [comment]
fixed in 83bc1c3
