### ISSUE TITLE
invalid token generated with synadm login

### ISSUE THREAD

**Issue by damnms** [JOJ0/synadm#134]
i use the following code to login:

```
root@vmyserver:/var/log/matrix-synapse# /home/matrix/venv/bin/synadm matrix login @mxx:matrix.mydomain.com
Password: 
user_id       @mxx:matrix.mydomain.com
access_token  syt_b....yd
home_server   matrix.mydomain.com
device_id     ...
well_known    {'m.homeserver': {'base_url': 'https://matrix.mydomain.com/'}}
```
and it looks ok to me, because i get the output. now i'd like to list the users on my server:
```

root@vmyserver:/var/log/matrix-synapse# /home/matrix/venv/bin/synadm user list
WARNING Synapse returned status code 401
Traceback (most recent call last):
  File "/home/matrix/venv/bin/synadm", line 8, in <module>
    sys.exit(root())
             ^^^^^^
  File "/home/matrix/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matrix/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/matrix/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matrix/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matrix/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matrix/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matrix/venv/lib/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matrix/venv/lib/python3.11/site-packages/synadm/cli/user.py", line 86, in list_user_cmd
    .format(users["total"]))
            ~~~~~^^^^^^^^^
KeyError: 'total'
```

when i check my log, it says:
`2023-10-20 09:53:41,815 - synapse.http.server - 124 - INFO - GET-1535 - <XForwardedForRequest at 0x7f3325683110 method='GET' uri='/_synapse/admin/v2/users?from=0&limit=100' clientproto='HTTP/1.1' site='8008'> SynapseError: 401 - Invalid access token passed.`

i use version 0.44

not sure if i do something wrong or if this is some kind of bug?

**Comment by damnms** [comment]
thanks, that indeed solved it ;)
