### ISSUE TITLE
list index errors on pagination with --from <number>

### ISSUE THREAD

**Issue by JOJ0** [JOJ0/synadm#36]
when paginating through results and --from number is too high index error should be catched:

```
jojo@jum ~/git/synadm (media) $ synadm -o human media list -u @testuser1:peek-a-boo.at -f 1019
User has uploaded 1019 media blobs.
Traceback (most recent call last):
  File "/usr/local/bin/synadm", line 11, in <module>
    load_entry_point('synadm', 'console_scripts', 'synadm')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jojo/git/synadm/synadm/cli/media.py", line 83, in media_list_cmd
    from_=from_, limit=limit, sort=sort, reverse=reverse)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/jojo/git/synadm/synadm/cli/user.py", line 396, in user_media_cmd
    helper.output(media["media"])
  File "/home/jojo/git/synadm/synadm/cli/__init__.py", line 172, in output
    click.echo(self.formatter(data))
  File "/home/jojo/git/synadm/synadm/cli/__init__.py", line 39, in humanize
    if isinstance(data, list) and isinstance(data[0], dict):
IndexError: list index out of range
```

applies to commands: `media list`, `user list`, `room list` and probably more....FIXME

**Comment by JOJ0** [comment]
Fixed
