### ISSUE TITLE
synadm stopped functioning on server

### ISSUE THREAD

**Issue by jahway603** [JOJ0/synadm#75]
Before today, I have successfully ran synadm on this Matrix Synapse server. I'm not sure the last time I checked the functionality on this server as it is a single-user server. It was upgraded to the latest Matrix Synapse, which was released today/yesterday, of version 1.67.0. This may have been working perfectly fine with Matrix Synapse v 1.66.0, but again not sure when I last used it on this server.

System OS: Debian 11 Bullseye

Today, it will not function, and this is the output I receive:

```
$ synadm user list
WARNING Synapse returned status code 401
Traceback (most recent call last):
  File "/usr/local/bin/synadm", line 33, in <module>
    sys.exit(load_entry_point('synadm==0.36', 'console_scripts', 'synadm')())
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/synadm-0.36-py3.9.egg/synadm/cli/user.py", line 80, in list_user_cmd
KeyError: 'total'
```

I then followed the upgrade instructions in the README.md, but afterwards I receive the same error message.

**Comment by jahway603** [comment]
In contrast, I have a completely different Matrix Synapse server (v 1.66.0) where synadm works perfectly fine. I will see what I can figure out on this end, but wanted to report the issue I was seeing.

**Comment by JOJ0** [comment]
There might be changes in 1.67 with the user api endpoint. The key mentionend (total) is indeed something synadm tries to find and print.

Please try other commands as well, not only user list. Also please send reports with synadm -vv ..., it helps understand what's happening in the background. Redact your token in the output before sending!!

**Comment by jahway603** [comment]
I tried some other commands, like `synadm room list`, and they all bombed. I then backed up the ~/.config/synadm.yaml and ran `synadm config`, but got the same results. Then I double checked the token in the synadm.yaml against the one in the Element client, which was now different, so I updated the synadm.yaml with it & now it works. Not sure why the key changed. Closing this issue as resolved.

**Comment by JOJ0** [comment]
@Ascurius I now see that actually synapse simply returned a 401 unauthorized. We could try catching errors like this more elegantly, and maybe suggesting the user could check authorization info.
